Router.map ->
  @route 'memberships',
    controller: ShopAdminController
    path: 'dashboard/settings/memberships',
    template: 'memberships'
    waitOn: ->
      return ReactionCore.Subscriptions.Packages
  @route 'createMembershipType',
  	controller: ShopAdminController
  	path: 'dashboard/create-new-membership-type'
  	template: 'createNewMembershipType'
  	waitOn: ->
  		return ReactionCore.Subscriptions.Packages